server.port: 8888
spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    enabled: false
        # git:
        #   uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
        #   default-label: main
        # native:
        #   searchLocations: file:///${GIT_REPO}

