services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  customers-service:
    image: ${CUSTOMERS_IMAGE}
    container_name: customers-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SERVER_PORT: ${CUSTOMERS_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: ${SPRING_JPA_DEFER}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_DDL}
      SPRING_SQL_INIT_SCHEMA_LOCATIONS: ${SPRING_SCHEMA_LOC}
      SPRING_SQL_INIT_DATA_LOCATIONS: ${SPRING_DATA_LOC}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS}

      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CONFIG_IMPORT: ""
    depends_on:
      - mysql
    ports:
      - "${CUSTOMERS_PORT}:${CUSTOMERS_PORT}"

  visits-service:
    image: ${VISITS_IMAGE}
    container_name: visits-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SERVER_PORT: ${VISITS_PORT}
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED: "false"
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: ${SPRING_JPA_DEFER}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_DDL}
      SPRING_SQL_INIT_SCHEMA_LOCATIONS: ${SPRING_SCHEMA_LOC}
      SPRING_SQL_INIT_DATA_LOCATIONS: ${SPRING_DATA_LOC}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS}
    depends_on:
      - mysql
      - customers-service
    ports:
      - "${VISITS_PORT}:${VISITS_PORT}"

  vets-service:
    image: ${VETS_IMAGE}
    container_name: vets-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SERVER_PORT: ${VETS_PORT}
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED: "false"
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: ${SPRING_JPA_DEFER}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_DDL}
      SPRING_SQL_INIT_SCHEMA_LOCATIONS: ${SPRING_SCHEMA_LOC}
      SPRING_SQL_INIT_DATA_LOCATIONS: ${SPRING_DATA_LOC}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS}
    depends_on:
      - mysql
    ports:
      - "${VETS_PORT}:${VETS_PORT}"

  genai-service:
    image: ${GENAI_IMAGE}
    container_name: genai-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SERVER_PORT: ${GENAI_PORT}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS}
    ports:
      - "${GENAI_PORT}:${GENAI_PORT}"

  api-gateway:
    image: ${GATEWAY_IMAGE}
    container_name: api-gateway
    environment:
      SERVER_PORT: ${GATEWAY_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED: "false"
      EUREKA_CLIENT_ENABLED: "false"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${GATEWAY_MANAGEMENT}
      CUSTOMERS_SERVICE_URL: ${CUSTOMERS_SERVICE_URL}
      VETS_SERVICE_URL: ${VETS_SERVICE_URL}
      VISITS_SERVICE_URL: ${VISITS_SERVICE_URL}
      GENAI_SERVICE_URL: ${GENAI_SERVICE_URL}
    depends_on:
      - customers-service
      - vets-service
      - visits-service
      - genai-service
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
      
  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    ports:
      - "${GRAFANA_PORT}:3000"

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    ports:
      - "${PROMETHEUS_PORT}:9090"

volumes:
  mysql-data: