apiVersion: v1
kind: ConfigMap
metadata:
  name: visits-service-config
  namespace: petclinic
data:
  application.yml: |
    spring:
      application:
        name: visits-service
      profiles:
        active: docker
      cloud:
        config:
          enabled: false
      datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
      sql:
        init:
          mode: always
          schema-locations: classpath:/db/mysql/schema.sql
          data-locations: classpath:/db/mysql/data.sql
      jpa:
        defer-datasource-initialization: false
        hibernate:
          ddl-auto: none

    server:
      port: 8082

    eureka:
      client:
        enabled: false

    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus