server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: customers-service
              uri: ${CUSTOMERS_SERVICE_URL}
              predicates:
                - Path=/api/customer/**
              filters:
                - StripPrefix=2
            - id: vets-service
              uri: ${VETS_SERVICE_URL}
              predicates:
                - Path=/api/vet/**
              filters:
                - StripPrefix=2
            - id: visits-service
              uri: ${VISITS_SERVICE_URL}
              predicates:
                - Path=/api/visit/**
              filters:
                - StripPrefix=2
            - id: genai-service
              uri: ${GENAI_SERVICE_URL}
              predicates:
                - Path=/api/genai/**
              filters:
                - StripPrefix=2


eureka:
  client:
    enabled: false

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway,mappings